name: CI de nuestra app

on:
    push:
        branches:
            - main

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hola Mundo"

            - name: Listar archivos
              run: ls -la

            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Listar archivos post checkout
              run: ls -la

            - name: Install NodeJs
              uses: actions/setup-node@v3
              with:
                  node-version: '20'

            - name: Install dependencies
              run: npm install
            
            - name: Run tests
              run: npm test